name: Testing
on: push

jobs:
    test_project:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Run Django unit tests
          run: |
            sudo apt-get install python3-setuptools  
            pip3 install --user -r requirements.txt
            cd myregister
            python3 manage.py makemigrations
            python3 manage.py migrate
            python3 manage.py test
